### ISSUE TITLE
Add --latest option

### ISSUE THREAD

**Issue by perlun** [perlun/changelog-rs#11]
I often find myself using the tool like this:

```
$ changelog-rs . | head -n20
```

...to get the _just_ for the latest version. It would be good if there was a command line option for this instead.

**Comment by perlun** [comment]
(I was just thinking of filing an issue for this, but apparently I already filed it 1,5 month ago. 😆)

**Comment by liamdawson** [comment]
Didn't you add this already? :slightly_smiling_face:

**Comment by perlun** [comment]
Correct - implemented in 6d47f1aeabe3c3e43edf59ef883d073d3fcc5ad1. Thanks for noticing!
